### ISSUE TITLE
ENH: Allow users to specify unique settings for each PES-Averaged ARMC molecule

### ISSUE THREAD

**Issue by BvB93** [nlesc-nano/auto-FOX#171]
For example:
``` yaml
job:
    molecule: 
        - mol1.xyz
        - mol2.xyz
    md_settings:
        template: qmflows.templates.md.specific.cp2k_mm
        settings:
            - input: ... # Settings for molecule #1
            - input: ... # Settings for molecule #2
```
